services:
  pg_admindb:
    image: postgres:17
    container_name: pg_dda_admindb
    ports:
      - "5778:5432"
    environment:
      POSTGRES_DB: AdminDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PassSecure987
    volumes:
      - pg_admindbstore:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: unless-stopped


  dda_dsc_admin:
    build: .
    ports:
      - "6663:3333"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    depends_on:
      pg_admindb:
        condition: service_healthy

volumes:
  pg_admindbstore:
